FACTOR_MOE_CONFIG = {
    "csi300": {
        10: dict(
            market_hidden_dim=128,
            market_num_experts=8,
            market_chain_depth=3,
            market_num_heads=4,
            metric_chain_depth=2,
            metric_num_heads=3,
            metric_hidden_dim=32,
            metric_num_experts=2,
            market_bete=0.5,
            metric_bete=2,
            batch_size=8,
            epochs=10,
            windows=40,
            k=8,
        ),
    },
    "csi500": {
        10: dict(
            market_hidden_dim=256,
            market_chain_depth=3,
            market_num_heads=4,
            metric_hidden_dim=64,
            market_num_experts=8,
            metric_num_experts=2,
            metric_chain_depth=2,
            metric_num_heads=3,
            market_bete=0.5,
            metric_bete=2,
            batch_size=8,
            epochs=20,
            windows=40,
            k=8,
        ),
    },
    "csi800": {
        10: dict(
            market_hidden_dim=256,
            market_chain_depth=3,
            market_num_heads=12,
            metric_hidden_dim=32,
            market_num_experts=8,
            metric_num_experts=2,
            metric_chain_depth=2,
            metric_num_heads=3,
            market_bete=2,
            metric_bete=2,
            batch_size=8,
            epochs=10,
            windows=50,
            k=8,
        ),
    },
}
